export const CHANGE_SINCE_PARAM = "CHANGE_SINCE_PARAM";

export const CHANGE_LANGUAGE_PARAM = "CHANGE_LANGUAGE_PARAM";

export const CHANGE_START_SORT = "CHANGE_STAR_SORT";

export const GET_REPOS = "GET_REPOS";

export const REPOS_RECEIVED = "REPOS_RECEIVED";
